// <auto-generated />
using System;
using ACC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ACC.Data.Migrations
{
    [DbContext(typeof(ACCDbContext))]
    [Migration("20260309031110_SyncCurrentModelAfterReset")]
    partial class SyncCurrentModelAfterReset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("acc_academic")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ACC.Data.Entities.Agenda", b =>
                {
                    b.Property<int>("Id_Agenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Agenda"));

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id_Agenda");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Agendas", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Anuncio", b =>
                {
                    b.Property<int>("AnuncioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnuncioId"));

                    b.Property<int>("AulaId")
                        .HasColumnType("int");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocenteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AnuncioId");

                    b.HasIndex("AulaId", "Fecha");

                    b.ToTable("Anuncios", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAccion")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Auditorias", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Aula", b =>
                {
                    b.Property<int>("AulaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AulaId"));

                    b.Property<bool>("ArchivarAula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CerrarAula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocenteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SubModuloId")
                        .HasColumnType("int");

                    b.HasKey("AulaId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("SubModuloId");

                    b.HasIndex("ModuloId", "SubModuloId");

                    b.ToTable("Aulas", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.AulaEstudiante", b =>
                {
                    b.Property<int>("AulaEstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AulaEstudianteId"));

                    b.Property<int>("AulaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("AulaEstudianteId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("AulaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("AulaEstudiantes", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Aviso", b =>
                {
                    b.Property<int>("IdAviso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAviso"));

                    b.Property<int>("AulaId")
                        .HasColumnType("int");

                    b.Property<string>("ContenidoAviso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocenteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAviso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TituloAviso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdAviso");

                    b.HasIndex("AulaId");

                    b.ToTable("Avisos", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Capitulo", b =>
                {
                    b.Property<int>("IdCapitulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCapitulo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("LeccionId")
                        .HasColumnType("int");

                    b.Property<int?>("ModuloId")
                        .HasColumnType("int");

                    b.Property<int?>("SubmoduloId")
                        .HasColumnType("int");

                    b.Property<string>("SubtituloCapitulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TemaId")
                        .HasColumnType("int");

                    b.Property<string>("TituloCapitulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCapitulo");

                    b.HasIndex("LeccionId");

                    b.HasIndex("ModuloId");

                    b.HasIndex("SubmoduloId");

                    b.HasIndex("TemaId");

                    b.ToTable("Capitulos", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.CapituloTag", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("CapituloId")
                        .HasColumnType("int");

                    b.HasKey("TagId", "CapituloId");

                    b.HasIndex("CapituloId");

                    b.ToTable("CapituloTags", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.ContenidoCapitulo", b =>
                {
                    b.Property<int>("IdContenido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContenido"));

                    b.Property<int>("CapituloId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Dificultad")
                        .HasColumnType("int");

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconoBadge")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Subtitulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdContenido");

                    b.HasIndex("CapituloId");

                    b.ToTable("ContenidoCapitulos", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AulaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("AulaId", "Fecha");

                    b.ToTable("Evaluaciones", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.EvaluacionResultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Calificacion")
                        .HasColumnType("float");

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCalificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EvaluacionId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("EvaluacionResultados", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Examen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenidoHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroPreguntas")
                        .HasColumnType("int");

                    b.Property<int>("PuntajeAprobacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Examenes", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.ExamenAprobatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Calificacion")
                        .HasColumnType("float");

                    b.Property<int>("ExamenId")
                        .HasColumnType("int");

                    b.Property<int>("ExamenIntentoId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FechaAprobacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExamenIntentoId")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "Tipo", "ExamenId")
                        .IsUnique();

                    b.ToTable("ExamenesAprobatorios", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.ExamenHabilitado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("FechaHabilitacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<int>("RefId")
                        .HasColumnType("int");

                    b.Property<string>("ReglaFuente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Tipo", "RefId")
                        .IsUnique();

                    b.ToTable("ExamenesHabilitados", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.ExamenIntento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobado")
                        .HasColumnType("bit");

                    b.Property<double>("Calificacion")
                        .HasColumnType("float");

                    b.Property<int?>("ExamenId")
                        .HasColumnType("int");

                    b.Property<int?>("ExamenModuloId")
                        .HasColumnType("int");

                    b.Property<int?>("ExamenSubModuloId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FechaIntento")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumeroIntento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamenId");

                    b.HasIndex("ExamenModuloId");

                    b.HasIndex("ExamenSubModuloId");

                    b.HasIndex("IdUsuario", "ExamenId", "NumeroIntento")
                        .IsUnique()
                        .HasFilter("[ExamenId] IS NOT NULL");

                    b.HasIndex("IdUsuario", "ExamenModuloId", "NumeroIntento")
                        .IsUnique()
                        .HasFilter("[ExamenModuloId] IS NOT NULL");

                    b.HasIndex("IdUsuario", "ExamenSubModuloId", "Aprobado");

                    b.HasIndex("IdUsuario", "ExamenSubModuloId", "NumeroIntento")
                        .IsUnique()
                        .HasFilter("[ExamenSubModuloId] IS NOT NULL");

                    b.ToTable("ExamenesIntentos", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.ExamenModulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenidoHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroPreguntas")
                        .HasColumnType("int");

                    b.Property<int>("PuntajeAprobacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("ExamenesModulos", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.ExamenSubModulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenidoHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroPreguntas")
                        .HasColumnType("int");

                    b.Property<int>("PuntajeAprobacion")
                        .HasColumnType("int");

                    b.Property<int>("SubModuloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubModuloId");

                    b.ToTable("ExamenesSubModulo", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.HistorialCalificaciones", b =>
                {
                    b.Property<int>("Id_Historial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Historial"));

                    b.Property<decimal>("Calificacion")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("FechaCalificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_Modulo")
                        .HasColumnType("int");

                    b.Property<int?>("Id_SubModulo")
                        .HasColumnType("int");

                    b.Property<string>("Id_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id_Historial");

                    b.HasIndex("Id_Modulo");

                    b.HasIndex("Id_SubModulo");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("HistorialCalificaciones", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.InvitacionAula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("AulaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("ExpiraEn")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumUsos")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("AulaId", "Activa");

                    b.ToTable("InvitacionesAula", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Leccion", b =>
                {
                    b.Property<int>("IdLeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLeccion"));

                    b.Property<string>("CharpDialog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CharpTip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionLeccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ejemplo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelBloom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("OrdenSecciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Practica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubtemaId")
                        .HasColumnType("int");

                    b.Property<string>("Teoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TieneActividad")
                        .HasColumnType("bit");

                    b.Property<bool>("TieneCompilador")
                        .HasColumnType("bit");

                    b.Property<bool>("TieneVideo")
                        .HasColumnType("bit");

                    b.Property<string>("TituloLeccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlActividad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLeccion");

                    b.HasIndex("SubtemaId");

                    b.ToTable("Lecciones", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Modulo", b =>
                {
                    b.Property<int>("Id_Modulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Modulo"));

                    b.Property<string>("DescripcionModulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NombreModulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Modulo");

                    b.ToTable("Modulos", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.ModuloTags", b =>
                {
                    b.Property<int>("Id_Tag")
                        .HasColumnType("int");

                    b.Property<int>("Id_Modulo")
                        .HasColumnType("int");

                    b.HasKey("Id_Tag", "Id_Modulo");

                    b.HasIndex("Id_Modulo");

                    b.ToTable("ModuloTags", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AulaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("Leido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("AulaId", "FechaEnvio");

                    b.ToTable("Notificaciones", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.ProgresoUsuario", b =>
                {
                    b.Property<int>("IdProgreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProgreso"));

                    b.Property<bool>("Completado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SubTemaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdProgreso");

                    b.HasIndex("SubTemaId");

                    b.HasIndex("UsuarioId", "SubTemaId", "Completado");

                    b.ToTable("ProgresoUsuarios", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.SubModulo", b =>
                {
                    b.Property<int>("Id_SubModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_SubModulo"));

                    b.Property<string>("DescripcionSubModulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Id_Modulo")
                        .HasColumnType("int");

                    b.Property<string>("NombreSubModulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_SubModulo");

                    b.HasIndex("Id_Modulo");

                    b.ToTable("SubModulos", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.SubTema", b =>
                {
                    b.Property<int>("Id_SubTema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_SubTema"));

                    b.Property<string>("DescripcionSubTema")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Id_Tema")
                        .HasColumnType("int");

                    b.Property<string>("NombreSubTema")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_SubTema");

                    b.HasIndex("Id_Tema");

                    b.ToTable("SubTemas", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Tag", b =>
                {
                    b.Property<int>("IdTag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTag"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icono")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTag");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Tags", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Tarea", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaId"));

                    b.Property<int>("AulaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("TareaId");

                    b.HasIndex("AulaId", "FechaLimite");

                    b.ToTable("Tareas", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.TareaPersonal", b =>
                {
                    b.Property<int>("TareaPersonalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaPersonalId"));

                    b.Property<bool?>("Completada")
                        .HasColumnType("bit");

                    b.Property<int?>("IdAgenda")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TareaPersonalDescripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("TareaPersonalFechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<string>("TareaPersonalTitulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TareaPersonalId");

                    b.HasIndex("IdAgenda");

                    b.ToTable("TareasPersonales", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.TareasAsignaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Calificacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EstadoEntrega")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("Retroalimentacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TareaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TareaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("TareaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("TareasAsignaciones", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Tema", b =>
                {
                    b.Property<int>("Id_Tema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Tema"));

                    b.Property<string>("DescripcionTema")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Id_SubModulo")
                        .HasColumnType("int");

                    b.Property<string>("NombreTema")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UltimaVisita")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_Tema");

                    b.HasIndex("Id_SubModulo");

                    b.ToTable("Temas", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.TemaTags", b =>
                {
                    b.Property<int>("Id_Tag")
                        .HasColumnType("int");

                    b.Property<int>("Id_Tema")
                        .HasColumnType("int");

                    b.HasKey("Id_Tag", "Id_Tema");

                    b.HasIndex("Id_Tema");

                    b.ToTable("TemaTags", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Tip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Tips", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProgresoGeneral")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.UsuarioModulos", b =>
                {
                    b.Property<string>("Id_Usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id_Modulo")
                        .HasColumnType("int");

                    b.Property<decimal?>("Calificacion")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("EsCompletado")
                        .HasColumnType("bit");

                    b.Property<int>("Progreso")
                        .HasColumnType("int");

                    b.HasKey("Id_Usuario", "Id_Modulo");

                    b.HasIndex("Id_Modulo");

                    b.ToTable("UsuarioModulos", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.UsuarioSubModulos", b =>
                {
                    b.Property<string>("Id_Usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id_SubModulo")
                        .HasColumnType("int");

                    b.Property<decimal?>("Calificacion")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("EsCompletado")
                        .HasColumnType("bit");

                    b.Property<int>("Progreso")
                        .HasColumnType("int");

                    b.HasKey("Id_Usuario", "Id_SubModulo");

                    b.HasIndex("Id_SubModulo");

                    b.ToTable("UsuarioSubModulos", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.UsuarioSubTemas", b =>
                {
                    b.Property<string>("Id_Usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id_SubTema")
                        .HasColumnType("int");

                    b.Property<bool>("EsFavorito")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UltimaVisita")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_Usuario", "Id_SubTema");

                    b.HasIndex("Id_SubTema");

                    b.ToTable("UsuarioSubTemas", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.UsuarioTemas", b =>
                {
                    b.Property<string>("Id_Usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id_Tema")
                        .HasColumnType("int");

                    b.Property<bool>("EsFavorito")
                        .HasColumnType("bit");

                    b.Property<int>("Progreso")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaVisita")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_Usuario", "Id_Tema");

                    b.HasIndex("Id_Tema");

                    b.ToTable("UsuarioTemas", "acc_academic");
                });

            modelBuilder.Entity("ACC.Data.Entities.Agenda", b =>
                {
                    b.HasOne("ACC.Data.Entities.Usuario", "Usuario")
                        .WithOne("Agenda")
                        .HasForeignKey("ACC.Data.Entities.Agenda", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ACC.Data.Entities.Anuncio", b =>
                {
                    b.HasOne("ACC.Data.Entities.Aula", "Aula")
                        .WithMany("Anuncios")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aula");
                });

            modelBuilder.Entity("ACC.Data.Entities.Auditoria", b =>
                {
                    b.HasOne("ACC.Data.Entities.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ACC.Data.Entities.Aula", b =>
                {
                    b.HasOne("ACC.Data.Entities.Usuario", "Docente")
                        .WithMany("AulasDocente")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACC.Data.Entities.Modulo", "Modulo")
                        .WithMany("Aulas")
                        .HasForeignKey("ModuloId");

                    b.HasOne("ACC.Data.Entities.SubModulo", "SubModulo")
                        .WithMany()
                        .HasForeignKey("SubModuloId");

                    b.Navigation("Docente");

                    b.Navigation("Modulo");

                    b.Navigation("SubModulo");
                });

            modelBuilder.Entity("ACC.Data.Entities.AulaEstudiante", b =>
                {
                    b.HasOne("ACC.Data.Entities.Aula", "Aula")
                        .WithMany("AulaEstudiantes")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACC.Data.Entities.Usuario", "Usuario")
                        .WithMany("AulasEstudiantes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aula");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ACC.Data.Entities.Aviso", b =>
                {
                    b.HasOne("ACC.Data.Entities.Aula", "Aula")
                        .WithMany()
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aula");
                });

            modelBuilder.Entity("ACC.Data.Entities.Capitulo", b =>
                {
                    b.HasOne("ACC.Data.Entities.Leccion", "Leccion")
                        .WithMany("Capitulos")
                        .HasForeignKey("LeccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ACC.Data.Entities.Modulo", "Modulo")
                        .WithMany("Capitulos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ACC.Data.Entities.SubModulo", "SubModulo")
                        .WithMany("Capitulos")
                        .HasForeignKey("SubmoduloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ACC.Data.Entities.Tema", "Tema")
                        .WithMany("Capitulos")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Leccion");

                    b.Navigation("Modulo");

                    b.Navigation("SubModulo");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("ACC.Data.Entities.CapituloTag", b =>
                {
                    b.HasOne("ACC.Data.Entities.Capitulo", "Capitulo")
                        .WithMany("CapituloTags")
                        .HasForeignKey("CapituloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACC.Data.Entities.Tag", "Tag")
                        .WithMany("CapituloTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capitulo");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ACC.Data.Entities.ContenidoCapitulo", b =>
                {
                    b.HasOne("ACC.Data.Entities.Capitulo", "Capitulo")
                        .WithMany("Contenidos")
                        .HasForeignKey("CapituloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capitulo");
                });

            modelBuilder.Entity("ACC.Data.Entities.Evaluacion", b =>
                {
                    b.HasOne("ACC.Data.Entities.Aula", "Aula")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aula");
                });

            modelBuilder.Entity("ACC.Data.Entities.EvaluacionResultado", b =>
                {
                    b.HasOne("ACC.Data.Entities.Evaluacion", "Evaluacion")
                        .WithMany("Resultados")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACC.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ACC.Data.Entities.ExamenAprobatorio", b =>
                {
                    b.HasOne("ACC.Data.Entities.ExamenIntento", "ExamenIntento")
                        .WithMany()
                        .HasForeignKey("ExamenIntentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACC.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamenIntento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ACC.Data.Entities.ExamenIntento", b =>
                {
                    b.HasOne("ACC.Data.Entities.Examen", "Examen")
                        .WithMany("Intentos")
                        .HasForeignKey("ExamenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ACC.Data.Entities.ExamenModulo", "ExamenModulo")
                        .WithMany("Intentos")
                        .HasForeignKey("ExamenModuloId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ACC.Data.Entities.ExamenSubModulo", "ExamenSubModulo")
                        .WithMany("Intentos")
                        .HasForeignKey("ExamenSubModuloId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ACC.Data.Entities.Usuario", "Usuario")
                        .WithMany("Intentos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Examen");

                    b.Navigation("ExamenModulo");

                    b.Navigation("ExamenSubModulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ACC.Data.Entities.ExamenModulo", b =>
                {
                    b.HasOne("ACC.Data.Entities.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("ACC.Data.Entities.ExamenSubModulo", b =>
                {
                    b.HasOne("ACC.Data.Entities.SubModulo", "SubModulo")
                        .WithMany("Examenes")
                        .HasForeignKey("SubModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubModulo");
                });

            modelBuilder.Entity("ACC.Data.Entities.HistorialCalificaciones", b =>
                {
                    b.HasOne("ACC.Data.Entities.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("Id_Modulo");

                    b.HasOne("ACC.Data.Entities.SubModulo", "SubModulo")
                        .WithMany()
                        .HasForeignKey("Id_SubModulo");

                    b.HasOne("ACC.Data.Entities.Usuario", "Usuario")
                        .WithMany("HistorialCalificaciones")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("SubModulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ACC.Data.Entities.InvitacionAula", b =>
                {
                    b.HasOne("ACC.Data.Entities.Aula", "Aula")
                        .WithMany("Invitaciones")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aula");
                });

            modelBuilder.Entity("ACC.Data.Entities.Leccion", b =>
                {
                    b.HasOne("ACC.Data.Entities.SubTema", "SubTema")
                        .WithMany("Lecciones")
                        .HasForeignKey("SubtemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubTema");
                });

            modelBuilder.Entity("ACC.Data.Entities.ModuloTags", b =>
                {
                    b.HasOne("ACC.Data.Entities.Modulo", "Modulo")
                        .WithMany("ModuloTags")
                        .HasForeignKey("Id_Modulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACC.Data.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("Id_Tag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ACC.Data.Entities.Notificacion", b =>
                {
                    b.HasOne("ACC.Data.Entities.Aula", "Aula")
                        .WithMany("Notificaciones")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ACC.Data.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aula");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ACC.Data.Entities.ProgresoUsuario", b =>
                {
                    b.HasOne("ACC.Data.Entities.SubTema", "SubTema")
                        .WithMany()
                        .HasForeignKey("SubTemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubTema");
                });

            modelBuilder.Entity("ACC.Data.Entities.SubModulo", b =>
                {
                    b.HasOne("ACC.Data.Entities.Modulo", "Modulo")
                        .WithMany("SubModulos")
                        .HasForeignKey("Id_Modulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("ACC.Data.Entities.SubTema", b =>
                {
                    b.HasOne("ACC.Data.Entities.Tema", "Tema")
                        .WithMany("SubTemas")
                        .HasForeignKey("Id_Tema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("ACC.Data.Entities.Tarea", b =>
                {
                    b.HasOne("ACC.Data.Entities.Aula", "Aula")
                        .WithMany("Tareas")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aula");
                });

            modelBuilder.Entity("ACC.Data.Entities.TareaPersonal", b =>
                {
                    b.HasOne("ACC.Data.Entities.Agenda", "Agenda")
                        .WithMany("TareasPersonales")
                        .HasForeignKey("IdAgenda");

                    b.Navigation("Agenda");
                });

            modelBuilder.Entity("ACC.Data.Entities.TareasAsignaciones", b =>
                {
                    b.HasOne("ACC.Data.Entities.Tarea", "Tarea")
                        .WithMany("Asignaciones")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACC.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ACC.Data.Entities.Tema", b =>
                {
                    b.HasOne("ACC.Data.Entities.SubModulo", "SubModulo")
                        .WithMany("Temas")
                        .HasForeignKey("Id_SubModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubModulo");
                });

            modelBuilder.Entity("ACC.Data.Entities.TemaTags", b =>
                {
                    b.HasOne("ACC.Data.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("Id_Tag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACC.Data.Entities.Tema", "Tema")
                        .WithMany("TemaTags")
                        .HasForeignKey("Id_Tema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("ACC.Data.Entities.UsuarioModulos", b =>
                {
                    b.HasOne("ACC.Data.Entities.Modulo", "Modulo")
                        .WithMany("UsuarioModulos")
                        .HasForeignKey("Id_Modulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACC.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ACC.Data.Entities.UsuarioSubModulos", b =>
                {
                    b.HasOne("ACC.Data.Entities.SubModulo", "SubModulo")
                        .WithMany("UsuarioSubModulos")
                        .HasForeignKey("Id_SubModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACC.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubModulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ACC.Data.Entities.UsuarioSubTemas", b =>
                {
                    b.HasOne("ACC.Data.Entities.SubTema", "SubTema")
                        .WithMany("UsuarioSubTemas")
                        .HasForeignKey("Id_SubTema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACC.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubTema");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ACC.Data.Entities.UsuarioTemas", b =>
                {
                    b.HasOne("ACC.Data.Entities.Tema", "Tema")
                        .WithMany("UsuarioTemas")
                        .HasForeignKey("Id_Tema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACC.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tema");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ACC.Data.Entities.Agenda", b =>
                {
                    b.Navigation("TareasPersonales");
                });

            modelBuilder.Entity("ACC.Data.Entities.Aula", b =>
                {
                    b.Navigation("Anuncios");

                    b.Navigation("AulaEstudiantes");

                    b.Navigation("Evaluaciones");

                    b.Navigation("Invitaciones");

                    b.Navigation("Notificaciones");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("ACC.Data.Entities.Capitulo", b =>
                {
                    b.Navigation("CapituloTags");

                    b.Navigation("Contenidos");
                });

            modelBuilder.Entity("ACC.Data.Entities.Evaluacion", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("ACC.Data.Entities.Examen", b =>
                {
                    b.Navigation("Intentos");
                });

            modelBuilder.Entity("ACC.Data.Entities.ExamenModulo", b =>
                {
                    b.Navigation("Intentos");
                });

            modelBuilder.Entity("ACC.Data.Entities.ExamenSubModulo", b =>
                {
                    b.Navigation("Intentos");
                });

            modelBuilder.Entity("ACC.Data.Entities.Leccion", b =>
                {
                    b.Navigation("Capitulos");
                });

            modelBuilder.Entity("ACC.Data.Entities.Modulo", b =>
                {
                    b.Navigation("Aulas");

                    b.Navigation("Capitulos");

                    b.Navigation("ModuloTags");

                    b.Navigation("SubModulos");

                    b.Navigation("UsuarioModulos");
                });

            modelBuilder.Entity("ACC.Data.Entities.SubModulo", b =>
                {
                    b.Navigation("Capitulos");

                    b.Navigation("Examenes");

                    b.Navigation("Temas");

                    b.Navigation("UsuarioSubModulos");
                });

            modelBuilder.Entity("ACC.Data.Entities.SubTema", b =>
                {
                    b.Navigation("Lecciones");

                    b.Navigation("UsuarioSubTemas");
                });

            modelBuilder.Entity("ACC.Data.Entities.Tag", b =>
                {
                    b.Navigation("CapituloTags");
                });

            modelBuilder.Entity("ACC.Data.Entities.Tarea", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("ACC.Data.Entities.Tema", b =>
                {
                    b.Navigation("Capitulos");

                    b.Navigation("SubTemas");

                    b.Navigation("TemaTags");

                    b.Navigation("UsuarioTemas");
                });

            modelBuilder.Entity("ACC.Data.Entities.Usuario", b =>
                {
                    b.Navigation("Agenda")
                        .IsRequired();

                    b.Navigation("Auditorias");

                    b.Navigation("AulasDocente");

                    b.Navigation("AulasEstudiantes");

                    b.Navigation("HistorialCalificaciones");

                    b.Navigation("Intentos");

                    b.Navigation("Notificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
