-- Propuesta de recreacion de tips (solo revision, no ejecutado)
-- Fuente: lista proporcionada por el usuario
-- Tabla objetivo: [ACC_Academic].[acc_academic].[Tips]

USE [ACC_Academic];
GO

INSERT INTO [acc_academic].[Tips] ([Contenido]) VALUES
(N'Usa nombres claros para variables y metodos.'),
(N'Si un bloque de codigo es dificil de explicar, probablemente es dificil de mantener.'),
(N'Divide el codigo grande en metodos pequenos.'),
(N'Evita repetir el mismo codigo en varios lugares.'),
(N'Si algo se repite mucho, conviertelo en funcion o metodo.'),
(N'El codigo claro vale mas que el codigo ingenioso.'),
(N'Elimina codigo que ya no se usa.'),
(N'Un buen nombre evita muchos comentarios.'),
(N'Escribe comentarios para explicar decisiones, no lo obvio.'),
(N'Si el codigo parece confuso, intenta simplificarlo.'),
(N'Cada clase deberia tener una responsabilidad clara.'),
(N'Si una clase hace demasiadas cosas, dividela.'),
(N'Manten la logica de negocio separada de la interfaz.'),
(N'Prefiere interfaces cuando disenes servicios.'),
(N'Evita dependencias innecesarias entre modulos.'),
(N'Disena funciones faciles de probar.'),
(N'No conviertas todo en arquitectura compleja si no hace falta.'),
(N'La simplicidad suele ser la mejor solucion.'),
(N'Manten los modulos pequenos y faciles de entender.'),
(N'Disena pensando en mantenimiento futuro.'),
(N'No ignores errores silenciosamente.'),
(N'Siempre registra errores importantes en logs.'),
(N'Los mensajes de error deben ayudar a entender el problema.'),
(N'No uses excepciones genericas si puedes usar una mas especifica.'),
(N'Si algo puede fallar, preparate para manejar ese caso.'),
(N'Valida los datos cuando entran al sistema.'),
(N'No confies en que el usuario siempre enviara datos correctos.'),
(N'Antes de corregir un bug, intenta reproducirlo.'),
(N'Un buen log puede ahorrar horas de depuracion.'),
(N'Nunca ocultes un error sin registrar contexto.'),
(N'Usa var cuando el tipo sea obvio.'),
(N'Si el tipo no es obvio, escribelo completo.'),
(N'Evita async void excepto en eventos.'),
(N'Prefiere Task o Task<T> en metodos asincronos.'),
(N'No bloquees codigo async con .Result o .Wait().'),
(N'Usa using para cerrar recursos correctamente.'),
(N'Evita estado global con variables static.'),
(N'Usa record para datos que no cambian.'),
(N'Prefiere propiedades simples cuando no hay logica extra.'),
(N'Manten metodos cortos y faciles de leer.'),
(N'Consulta solo los datos que necesitas.'),
(N'Usa AsNoTracking cuando solo vayas a leer datos.'),
(N'Evita cargar grandes cantidades de datos sin necesidad.'),
(N'Usa indices en columnas que se consultan mucho.'),
(N'Revisa bien las relaciones antes de crear migraciones.'),
(N'Haz respaldo antes de modificar estructuras importantes.'),
(N'No confies en la intuicion para rendimiento: mide.'),
(N'Evita consultas complejas dentro de loops.'),
(N'Si una consulta es lenta, revisa su plan de ejecucion.'),
(N'Disena la base pensando en como se consultaran los datos.'),
(N'Un endpoint debe tener un proposito claro.'),
(N'Usa codigos HTTP correctos en tus respuestas.'),
(N'No devuelvas mensajes de error ambiguos.'),
(N'Manten el contrato de la API estable.'),
(N'Evita romper compatibilidad sin aviso.'),
(N'Define timeouts para llamadas a servicios externos.'),
(N'Centraliza la configuracion de tu aplicacion.'),
(N'No guardes secretos directamente en el codigo.'),
(N'Traduce errores tecnicos a mensajes utiles para el cliente.'),
(N'Disena APIs faciles de entender y consumir.'),
(N'Manten los componentes pequenos.'),
(N'Un componente deberia hacer una sola cosa.'),
(N'Evita logica pesada dentro de la interfaz.'),
(N'Usa servicios para manejar logica compleja.'),
(N'Reutiliza componentes cuando puedas.'),
(N'Evita duplicar codigo en varias vistas.'),
(N'Manten el estado de la aplicacion organizado.'),
(N'Divide interfaces grandes en componentes mas pequenos.'),
(N'Usa nombres claros para parametros de componentes.'),
(N'Una interfaz clara tambien mejora la experiencia del usuario.'),
(N'Usa el depurador antes de adivinar el problema.'),
(N'Coloca breakpoints para revisar el flujo del programa.'),
(N'Usa breakpoints condicionales para casos especificos.'),
(N'Revisa variables en Watch y Locals.'),
(N'Observa el stack trace cuando ocurre un error.'),
(N'Analiza el estado del programa antes de modificar codigo.'),
(N'Reproduce el error antes de intentar arreglarlo.'),
(N'No hagas muchos cambios al mismo tiempo.'),
(N'Cambios pequenos ayudan a encontrar la causa real.'),
(N'Los logs son aliados para entender errores.'),
(N'Haz commits pequenos y frecuentes.'),
(N'Escribe mensajes de commit claros.'),
(N'Revisa cambios con git diff antes de confirmar.'),
(N'No mezcles muchos cambios distintos en un solo commit.'),
(N'Antes de hacer merge, compila y prueba.'),
(N'Usa ramas para desarrollar nuevas funciones.'),
(N'No trabajes directamente en la rama principal.'),
(N'Un historial limpio facilita entender el proyecto.'),
(N'Git ayuda a recuperar cambios, pero no reemplaza backups.'),
(N'Revisa tu codigo antes de subirlo al repositorio.'),
(N'Aprende atajos de teclado para trabajar mas rapido.'),
(N'Usa renombrado automatico en lugar de cambiar nombres manualmente.'),
(N'La busqueda global es muy util para entender un proyecto.'),
(N'Activa formateo automatico al guardar archivos.'),
(N'Usa snippets para escribir codigo repetitivo.'),
(N'Manten pocas extensiones, pero bien elegidas.'),
(N'Usa Go to Definition para navegar rapido por el codigo.'),
(N'Usa Find All References para entender donde se usa algo.'),
(N'Configura EditorConfig para mantener estilo consistente.'),
(N'Manten tu entorno de desarrollo limpio y ordenado.'),
(N'No ejecutes comandos destructivos sin revisarlos primero.'),
(N'Haz respaldo antes de cambios grandes.'),
(N'Si no entiendes un comando, investigalo antes de ejecutarlo.'),
(N'Documenta decisiones tecnicas importantes.'),
(N'Un buen README ayuda a todo el equipo.'),
(N'Automatiza tareas repetitivas cuando sea posible.'),
(N'La velocidad sin control genera errores costosos.'),
(N'Aprende de cada bug que encuentres.'),
(N'La comunicacion tecnica clara evita retrabajo.'),
(N'La mejor herramienta de un programador es el criterio.'),
(N'¡Grapefruit the best!');
GO
